# Generated by Django 5.2.4 on 2025-08-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('clases_incluidas', models.ManyToManyField(related_name='planes_con_clase', to='planes.clases')),
            ],
        ),
        migrations.DeleteModel(
            name='Beneficio',
        ),
        migrations.DeleteModel(
            name='Planes',
        ),
    ]
